

services:
  gateway:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_HTTP_PORTS=8080
    ports:
     - 8080:8080

  coursesapi:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_HTTP_PORTS=8080
    - ConnectionStrings__CoursesApiContext=Server=sqldata;Database=CourseDB;User Id=sa;Password=!ADOPON2002;Encrypt=False
    - MessageBroker__Host=amqp://adopon:!ADOPON2002@rabbitmq:5672
    ports:
    - "5081:8080"

  studentsapi:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development        
    - ASPNETCORE_HTTP_PORTS=8080
    - ConnectionStrings__StudentsAPIContext=Server=sqldata;Database=StudentDB;User Id=sa;Password=!ADOPON2002;Encrypt=False
    - MessageBroker__Host=amqp://adopon:!ADOPON2002@rabbitmq:5672

    ports:
    - "5082:8080"

  sqldata:
    environment:
    - SA_PASSWORD=!ADOPON2002
    - ACCEPT_EULA=Y
    ports:
    - "1433:1433"
    volumes:
    - lab2-sqldata:/var/opt/mssql
    
  rabbitmq:
   ports:
       - 5672:5672
       - 15672:15672
   environment:
     - RABBITMQ_DEFAULT_USER=adopon
     - RABBITMQ_DEFAULT_PASS=!ADOPON2002

volumes:
   lab2-sqldata:
     external: false