apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f compose.yml2
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f compose.yml2
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/individualusdarbas-default: "true"
        io.kompose.service: gateway
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          image: adas291/apigateway
          name: gateway
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
