apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f compose.yml2
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: studentsapi
  name: studentsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: studentsapi
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f compose.yml2
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/individualusdarbas-default: "true"
        io.kompose.service: studentsapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__StudentsAPIContext
              value: Server=sqldata;Database=StudentDB;User Id=sa;Password=!ADOPON2002;Encrypt=False
            - name: MessageBroker__Host
              value: amqp://adopon:!ADOPON2002@rabbitmq:5672
          image: adas291/studentsapi
          name: studentsapi
          ports:
            - containerPort: 8080
              hostPort: 5082
              protocol: TCP
      restartPolicy: Always
