apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f compose.yml2
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: studentsapi
  name: studentsapi
spec:
  ports:
    - name: "5082"
      port: 5082
      targetPort: 8080
  selector:
    io.kompose.service: studentsapi
